/**
 * Balance Sheet Report Template
 * Provides bilingual (English/Turkish) labels and formatting for Balance Sheet reports.
 * 
 * @module templates/reports/balanceSheet
 */

/**
 * Balance Sheet report labels in both languages.
 * @type {Object}
 */
const labels = {
  en: {
    // Report title
    title: 'Balance Sheet',
    subtitle: 'Statement of Financial Position',
    
    // Date label
    asOfDate: 'As of Date',
    
    // Assets section
    assetsSectionTitle: 'Assets',
    currentAssets: 'Current Assets',
    fixedAssets: 'Fixed Assets',
    intangibleAssets: 'Intangible Assets',
    totalAssets: 'Total Assets',
    
    // Liabilities section
    liabilitiesSectionTitle: 'Liabilities',
    currentLiabilities: 'Current Liabilities',
    longTermLiabilities: 'Long-term Liabilities',
    totalLiabilities: 'Total Liabilities',
    
    // Equity section
    equitySectionTitle: 'Equity',
    shareCapital: 'Share Capital',
    retainedEarnings: 'Retained Earnings',
    currentPeriodEarnings: 'Current Period Earnings',
    reserves: 'Reserves',
    totalEquity: 'Total Equity',
    
    // Summary
    totalLiabilitiesAndEquity: 'Total Liabilities & Equity',
    balanceCheck: 'Balance Check',
    balanced: 'Balanced',
    notBalanced: 'NOT BALANCED',
    discrepancy: 'Discrepancy',
    
    // Table headers
    categoryCode: 'Code',
    category: 'Category',
    amount: 'Amount',
    previousPeriod: 'Previous Period',
    change: 'Change',
    
    // Period labels
    asOf: 'As of',
    generatedOn: 'Generated On',
    taxYear: 'Tax Year',
    
    // Comparison
    comparison: {
      previous: 'Previous Period',
      change: 'Change',
      percentChange: '% Change'
    },
    
    // Footer
    footer: {
      disclaimer: 'This report is for informational purposes only and does not constitute professional tax advice.',
      confidential: 'Confidential',
      generatedBy: 'Generated by UK Accounting System',
      accountingBasis: 'Prepared on an accrual accounting basis'
    }
  },
  
  tr: {
    // Report title
    title: 'Bilanço',
    subtitle: 'Finansal Durum Tablosu',
    
    // Date label
    asOfDate: 'Tarih İtibariyle',
    
    // Assets section
    assetsSectionTitle: 'Varlıklar',
    currentAssets: 'Dönen Varlıklar',
    fixedAssets: 'Duran Varlıklar',
    intangibleAssets: 'Maddi Olmayan Varlıklar',
    totalAssets: 'Toplam Varlıklar',
    
    // Liabilities section
    liabilitiesSectionTitle: 'Yükümlülükler',
    currentLiabilities: 'Kısa Vadeli Yükümlülükler',
    longTermLiabilities: 'Uzun Vadeli Yükümlülükler',
    totalLiabilities: 'Toplam Yükümlülükler',
    
    // Equity section
    equitySectionTitle: 'Öz Sermaye',
    shareCapital: 'Sermaye',
    retainedEarnings: 'Dağıtılmamış Karlar',
    currentPeriodEarnings: 'Cari Dönem Karı',
    reserves: 'Yedekler',
    totalEquity: 'Toplam Öz Sermaye',
    
    // Summary
    totalLiabilitiesAndEquity: 'Toplam Yükümlülükler ve Öz Sermaye',
    balanceCheck: 'Denge Kontrolü',
    balanced: 'Dengeli',
    notBalanced: 'DENGELİ DEĞİL',
    discrepancy: 'Fark',
    
    // Table headers
    categoryCode: 'Kod',
    category: 'Kategori',
    amount: 'Tutar',
    previousPeriod: 'Önceki Dönem',
    change: 'Değişim',
    
    // Period labels
    asOf: 'Tarihi itibariyle',
    generatedOn: 'Oluşturulma Tarihi',
    taxYear: 'Vergi Yılı',
    
    // Comparison
    comparison: {
      previous: 'Önceki Dönem',
      change: 'Değişim',
      percentChange: '% Değişim'
    },
    
    // Footer
    footer: {
      disclaimer: 'Bu rapor yalnızca bilgilendirme amaçlıdır ve profesyonel vergi tavsiyesi niteliği taşımaz.',
      confidential: 'Gizli',
      generatedBy: 'UK Muhasebe Sistemi tarafından oluşturulmuştur',
      accountingBasis: 'Tahakkuk esasına göre hazırlanmıştır'
    }
  }
};

/**
 * Gets labels for a specific language.
 * 
 * @param {string} [lang='en'] - Language code ('en' or 'tr')
 * @returns {Object} Labels for the specified language
 */
function getLabels(lang = 'en') {
  return labels[lang] || labels.en;
}

/**
 * PDF color theme for Balance Sheet reports.
 * @type {Object}
 */
const colors = {
  primary: '#1a365d',        // Dark blue for headers
  secondary: '#2b6cb0',      // Medium blue for accents
  text: '#1a202c',           // Near black for main text
  textLight: '#4a5568',      // Gray for secondary text
  border: '#e2e8f0',         // Light gray for borders
  background: '#f7fafc',     // Very light gray for backgrounds
  headerBg: '#edf2f7',       // Light blue-gray for table headers
  white: '#ffffff',
  
  // Section colors
  assets: '#2f855a',         // Green for assets
  liabilities: '#c53030',    // Red for liabilities
  equity: '#2b6cb0',         // Blue for equity
  
  // Status colors
  balanced: '#38a169',       // Green for balanced
  notBalanced: '#e53e3e',    // Red for not balanced
  
  // Change colors
  positive: '#38a169',       // Green for positive changes
  negative: '#e53e3e',       // Red for negative changes
  neutral: '#718096'         // Gray for no change
};

/**
 * PDF font settings.
 * @type {Object}
 */
const fonts = {
  regular: 'Helvetica',
  bold: 'Helvetica-Bold',
  italic: 'Helvetica-Oblique',
  boldItalic: 'Helvetica-BoldOblique'
};

/**
 * PDF layout settings for Balance Sheet reports.
 * @type {Object}
 */
const layout = {
  pageSize: 'A4',
  margins: {
    top: 50,
    bottom: 50,
    left: 50,
    right: 50
  },
  
  // Section spacing
  sectionSpacing: 20,
  lineSpacing: 5,
  
  // Table settings
  tableHeaderHeight: 22,
  tableRowHeight: 18,
  subtotalRowHeight: 20,
  totalRowHeight: 24,
  
  // Font sizes
  fontSize: {
    title: 18,
    subtitle: 12,
    sectionTitle: 12,
    subsectionTitle: 10,
    tableHeader: 9,
    tableCell: 9,
    footer: 8
  }
};

/**
 * Asset category classifications (based on UK chart of accounts).
 * @type {Object}
 */
const assetCategories = {
  currentAssets: {
    codeRange: [1000, 1299],
    codes: ['1000', '1010', '1100', '1101', '1200', '1210', '1220']
  },
  inventory: {
    codeRange: [1300, 1399],
    codes: ['1300', '1310', '1320', '1330']
  },
  fixedAssets: {
    codeRange: [1400, 1499],
    codes: ['1400', '1410', '1420', '1430', '1440', '1450']
  },
  intangibleAssets: {
    codeRange: [1500, 1599],
    codes: ['1500', '1510', '1520', '1530']
  }
};

/**
 * Liability category classifications (based on UK chart of accounts).
 * @type {Object}
 */
const liabilityCategories = {
  currentLiabilities: {
    codeRange: [2000, 2399],
    codes: ['2000', '2010', '2020', '2100', '2110', '2120', '2200', '2210', '2300']
  },
  longTermLiabilities: {
    codeRange: [2400, 2599],
    codes: ['2400', '2410', '2420', '2500']
  }
};

/**
 * Equity category classifications (based on UK chart of accounts).
 * @type {Object}
 */
const equityCategories = {
  shareCapital: {
    codeRange: [3000, 3099],
    codes: ['3000', '3010', '3020']
  },
  retainedEarnings: {
    codeRange: [3100, 3199],
    codes: ['3100']
  },
  reserves: {
    codeRange: [3200, 3299],
    codes: ['3200', '3210', '3220']
  }
};

module.exports = {
  labels,
  getLabels,
  colors,
  fonts,
  layout,
  assetCategories,
  liabilityCategories,
  equityCategories
};
