/**
 * Report Templates
 * Provides bilingual (English/Turkish) labels and formatting for UK-compliant financial reports.
 * 
 * Supported Reports:
 * - Profit & Loss (Income Statement)
 * - VAT Summary
 * - Cash Flow Statement
 * - PAYE Summary
 * 
 * @module templates/reports
 */

/**
 * Report labels in both languages.
 * @type {Object}
 */
const labels = {
  en: {
    // Report titles
    profitLoss: {
      title: 'Profit & Loss Report',
      subtitle: 'Income Statement',
      incomeSectionTitle: 'Income',
      expenseSectionTitle: 'Expenses',
      summarySectionTitle: 'Summary',
      monthlySectionTitle: 'Monthly Summary'
    },
    
    vatSummary: {
      title: 'VAT Summary Report',
      subtitle: 'Value Added Tax Summary',
      outputVatTitle: 'Output VAT (Sales)',
      inputVatTitle: 'Input VAT (Purchases)',
      netPositionTitle: 'Net VAT Position',
      byRateTitle: 'Breakdown by Rate',
      monthlyTitle: 'Monthly Breakdown'
    },
    
    cashFlow: {
      title: 'Cash Flow Statement',
      subtitle: 'Statement of Cash Flows',
      inflowsTitle: 'Cash Inflows',
      outflowsTitle: 'Cash Outflows',
      summaryTitle: 'Cash Summary',
      monthlyTitle: 'Monthly Cash Flow'
    },
    
    payeSummary: {
      title: 'PAYE Summary Report',
      subtitle: 'Pay As You Earn Summary',
      payrollTotalsTitle: 'Payroll Totals',
      hmrcLiabilityTitle: 'HMRC Liability',
      employeeBreakdownTitle: 'Employee Breakdown',
      monthlyTitle: 'Monthly Summary'
    },
    
    // Common labels
    common: {
      period: 'Report Period',
      taxYear: 'Tax Year',
      generatedOn: 'Generated On',
      page: 'Page',
      of: 'of',
      total: 'Total',
      subtotal: 'Subtotal',
      grandTotal: 'Grand Total',
      
      // Date and time
      date: 'Date',
      startDate: 'Start Date',
      endDate: 'End Date',
      
      // Financial terms
      amount: 'Amount',
      netAmount: 'Net Amount',
      vatAmount: 'VAT',
      grossAmount: 'Gross Amount',
      currency: '£',
      
      // Categories
      category: 'Category',
      categoryCode: 'Code',
      description: 'Description',
      
      // Counts
      transactionCount: 'Transactions',
      entriesCount: 'Entries',
      
      // Status
      yes: 'Yes',
      no: 'No',
      
      // Comparison
      previousPeriod: 'Previous Period',
      change: 'Change',
      percentChange: '% Change'
    },
    
    // Profit & Loss specific
    income: 'Income',
    expenses: 'Expenses',
    grossProfit: 'Gross Profit',
    netProfit: 'Net Profit',
    profitMargin: 'Profit Margin',
    
    // VAT specific
    vatRate: 'VAT Rate',
    outputVat: 'Output VAT',
    inputVat: 'Input VAT',
    netVat: 'Net VAT',
    vatPayable: 'VAT Payable to HMRC',
    vatRefund: 'VAT Refund Due from HMRC',
    
    // Cash Flow specific
    openingBalance: 'Opening Balance',
    closingBalance: 'Closing Balance',
    inflows: 'Cash Inflows',
    outflows: 'Cash Outflows',
    netCashChange: 'Net Cash Change',
    
    // PAYE specific
    employee: 'Employee',
    employeeNumber: 'Employee No.',
    firstName: 'First Name',
    lastName: 'Last Name',
    grossPay: 'Gross Pay',
    taxableIncome: 'Taxable Income',
    incomeTax: 'Income Tax',
    employeeNI: 'Employee NI',
    employerNI: 'Employer NI',
    totalNI: 'Total NI',
    studentLoan: 'Student Loan',
    pensionEmployee: 'Pension (Employee)',
    pensionEmployer: 'Pension (Employer)',
    netPay: 'Net Pay',
    totalPayrollCost: 'Total Payroll Cost',
    hmrcLiability: 'HMRC Liability',
    paymentDeadline: 'Payment Deadline',
    paye: 'PAYE',
    
    // Month names
    months: [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ],
    
    // Footer
    footer: {
      disclaimer: 'This report is for informational purposes only and does not constitute professional tax advice.',
      confidential: 'Confidential',
      generatedBy: 'Generated by UK Accounting System'
    }
  },
  
  tr: {
    // Report titles
    profitLoss: {
      title: 'Kar/Zarar Raporu',
      subtitle: 'Gelir Tablosu',
      incomeSectionTitle: 'Gelirler',
      expenseSectionTitle: 'Giderler',
      summarySectionTitle: 'Özet',
      monthlySectionTitle: 'Aylık Özet'
    },
    
    vatSummary: {
      title: 'KDV Özet Raporu',
      subtitle: 'Katma Değer Vergisi Özeti',
      outputVatTitle: 'Hesaplanan KDV (Satışlar)',
      inputVatTitle: 'İndirilecek KDV (Alışlar)',
      netPositionTitle: 'Net KDV Durumu',
      byRateTitle: 'Orana Göre Dağılım',
      monthlyTitle: 'Aylık Dağılım'
    },
    
    cashFlow: {
      title: 'Nakit Akış Tablosu',
      subtitle: 'Nakit Akışları Tablosu',
      inflowsTitle: 'Nakit Girişleri',
      outflowsTitle: 'Nakit Çıkışları',
      summaryTitle: 'Nakit Özeti',
      monthlyTitle: 'Aylık Nakit Akışı'
    },
    
    payeSummary: {
      title: 'PAYE Özet Raporu',
      subtitle: 'Bordro Vergi Özeti',
      payrollTotalsTitle: 'Bordro Toplamları',
      hmrcLiabilityTitle: 'HMRC Yükümlülüğü',
      employeeBreakdownTitle: 'Çalışan Dökümü',
      monthlyTitle: 'Aylık Özet'
    },
    
    // Common labels
    common: {
      period: 'Rapor Dönemi',
      taxYear: 'Vergi Yılı',
      generatedOn: 'Oluşturulma Tarihi',
      page: 'Sayfa',
      of: '/',
      total: 'Toplam',
      subtotal: 'Ara Toplam',
      grandTotal: 'Genel Toplam',
      
      // Date and time
      date: 'Tarih',
      startDate: 'Başlangıç Tarihi',
      endDate: 'Bitiş Tarihi',
      
      // Financial terms
      amount: 'Tutar',
      netAmount: 'Net Tutar',
      vatAmount: 'KDV',
      grossAmount: 'Brüt Tutar',
      currency: '£',
      
      // Categories
      category: 'Kategori',
      categoryCode: 'Kod',
      description: 'Açıklama',
      
      // Counts
      transactionCount: 'İşlem Sayısı',
      entriesCount: 'Kayıt Sayısı',
      
      // Status
      yes: 'Evet',
      no: 'Hayır',
      
      // Comparison
      previousPeriod: 'Önceki Dönem',
      change: 'Değişim',
      percentChange: '% Değişim'
    },
    
    // Profit & Loss specific
    income: 'Gelir',
    expenses: 'Giderler',
    grossProfit: 'Brüt Kar',
    netProfit: 'Net Kar',
    profitMargin: 'Kar Marjı',
    
    // VAT specific
    vatRate: 'KDV Oranı',
    outputVat: 'Hesaplanan KDV',
    inputVat: 'İndirilecek KDV',
    netVat: 'Net KDV',
    vatPayable: 'HMRC\'ye Ödenecek KDV',
    vatRefund: 'HMRC\'den Alınacak KDV İadesi',
    
    // Cash Flow specific
    openingBalance: 'Açılış Bakiyesi',
    closingBalance: 'Kapanış Bakiyesi',
    inflows: 'Nakit Girişleri',
    outflows: 'Nakit Çıkışları',
    netCashChange: 'Net Nakit Değişimi',
    
    // PAYE specific
    employee: 'Çalışan',
    employeeNumber: 'Çalışan No.',
    firstName: 'Ad',
    lastName: 'Soyad',
    grossPay: 'Brüt Ödeme',
    taxableIncome: 'Vergiye Tabi Gelir',
    incomeTax: 'Gelir Vergisi',
    employeeNI: 'Çalışan Ulusal Sigorta',
    employerNI: 'İşveren Ulusal Sigorta',
    totalNI: 'Toplam Ulusal Sigorta',
    studentLoan: 'Öğrenci Kredisi',
    pensionEmployee: 'Emeklilik (Çalışan)',
    pensionEmployer: 'Emeklilik (İşveren)',
    netPay: 'Net Ödeme',
    totalPayrollCost: 'Toplam Bordro Maliyeti',
    hmrcLiability: 'HMRC Yükümlülüğü',
    paymentDeadline: 'Ödeme Son Tarihi',
    paye: 'PAYE',
    
    // Month names
    months: [
      'Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran',
      'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık'
    ],
    
    // Footer
    footer: {
      disclaimer: 'Bu rapor yalnızca bilgilendirme amaçlıdır ve profesyonel vergi tavsiyesi niteliği taşımaz.',
      confidential: 'Gizli',
      generatedBy: 'UK Muhasebe Sistemi tarafından oluşturulmuştur'
    }
  }
};

/**
 * Gets labels for a specific language.
 * 
 * @param {string} [lang='en'] - Language code ('en' or 'tr')
 * @returns {Object} Labels for the specified language
 */
function getLabels(lang = 'en') {
  return labels[lang] || labels.en;
}

/**
 * Gets month name in the specified language.
 * 
 * @param {number} month - Month number (1-12)
 * @param {string} [lang='en'] - Language code
 * @returns {string} Month name
 */
function getMonthName(month, lang = 'en') {
  const l = getLabels(lang);
  return l.months[month - 1] || '';
}

/**
 * PDF color theme for reports.
 * @type {Object}
 */
const colors = {
  primary: '#1a365d',        // Dark blue for headers
  secondary: '#2b6cb0',      // Medium blue for accents
  text: '#1a202c',           // Near black for main text
  textLight: '#4a5568',      // Gray for secondary text
  border: '#e2e8f0',         // Light gray for borders
  background: '#f7fafc',     // Very light gray for backgrounds
  headerBg: '#edf2f7',       // Light blue-gray for table headers
  white: '#ffffff',
  
  // Report-specific colors
  income: '#38a169',         // Green for income/inflows
  expense: '#e53e3e',        // Red for expenses/outflows
  neutral: '#718096',        // Gray for neutral values
  positive: '#38a169',       // Green for positive changes
  negative: '#e53e3e'        // Red for negative changes
};

/**
 * PDF font settings.
 * @type {Object}
 */
const fonts = {
  regular: 'Helvetica',
  bold: 'Helvetica-Bold',
  italic: 'Helvetica-Oblique',
  boldItalic: 'Helvetica-BoldOblique'
};

/**
 * PDF layout settings for reports.
 * @type {Object}
 */
const layout = {
  pageSize: 'A4',
  margins: {
    top: 50,
    bottom: 50,
    left: 50,
    right: 50
  },
  
  // Header dimensions
  headerHeight: 80,
  
  // Table settings
  tableHeaderHeight: 22,
  tableRowHeight: 18,
  
  // Section spacing
  sectionSpacing: 25,
  lineSpacing: 5,
  
  // Font sizes
  fontSize: {
    title: 18,
    subtitle: 12,
    sectionTitle: 12,
    tableHeader: 9,
    tableCell: 9,
    footer: 8
  }
};

/**
 * VAT rate display names.
 * @type {Object}
 */
const vatRateNames = {
  en: {
    2000: 'Standard Rate (20%)',
    500: 'Reduced Rate (5%)',
    0: 'Zero Rate (0%)'
  },
  tr: {
    2000: 'Standart Oran (%20)',
    500: 'İndirimli Oran (%5)',
    0: 'Sıfır Oran (%0)'
  }
};

/**
 * Gets VAT rate display name.
 * 
 * @param {number} vatRate - VAT rate in basis points
 * @param {string} [lang='en'] - Language code
 * @returns {string} VAT rate display name
 */
function getVatRateName(vatRate, lang = 'en') {
  const names = vatRateNames[lang] || vatRateNames.en;
  if (names[vatRate]) {
    return names[vatRate];
  }
  const percentage = vatRate / 100;
  return lang === 'tr' ? `Özel Oran (%${percentage})` : `Custom Rate (${percentage}%)`;
}

module.exports = {
  labels,
  getLabels,
  getMonthName,
  colors,
  fonts,
  layout,
  vatRateNames,
  getVatRateName
};
