/**
 * Profit & Loss Report Template
 * Provides bilingual (English/Turkish) labels and formatting for Profit & Loss reports.
 * 
 * @module templates/reports/profitLoss
 */

/**
 * Profit & Loss report labels in both languages.
 * @type {Object}
 */
const labels = {
  en: {
    // Report title
    title: 'Profit & Loss Report',
    subtitle: 'Income Statement',
    
    // Section titles
    incomeSectionTitle: 'Income',
    expenseSectionTitle: 'Expenses',
    summarySectionTitle: 'Summary',
    monthlySectionTitle: 'Monthly Summary',
    
    // Summary labels
    income: 'Income',
    expenses: 'Expenses',
    grossProfit: 'Gross Profit',
    netProfit: 'Net Profit',
    profitMargin: 'Profit Margin',
    totalRevenue: 'Total Revenue',
    totalExpenses: 'Total Expenses',
    
    // Table headers
    categoryCode: 'Code',
    category: 'Category',
    amount: 'Amount',
    vatAmount: 'VAT',
    totalAmount: 'Total',
    transactionCount: 'Count',
    
    // Period labels
    period: 'Report Period',
    taxYear: 'Tax Year',
    from: 'From',
    to: 'To',
    generatedOn: 'Generated On',
    
    // Monthly breakdown
    month: 'Month',
    monthlyIncome: 'Income',
    monthlyExpenses: 'Expenses',
    monthlyNetProfit: 'Net Profit',
    
    // Footer
    footer: {
      disclaimer: 'This report is for informational purposes only and does not constitute professional tax advice.',
      confidential: 'Confidential',
      generatedBy: 'Generated by UK Accounting System'
    }
  },
  
  tr: {
    // Report title
    title: 'Kar/Zarar Raporu',
    subtitle: 'Gelir Tablosu',
    
    // Section titles
    incomeSectionTitle: 'Gelirler',
    expenseSectionTitle: 'Giderler',
    summarySectionTitle: 'Özet',
    monthlySectionTitle: 'Aylık Özet',
    
    // Summary labels
    income: 'Gelir',
    expenses: 'Giderler',
    grossProfit: 'Brüt Kar',
    netProfit: 'Net Kar',
    profitMargin: 'Kar Marjı',
    totalRevenue: 'Toplam Gelir',
    totalExpenses: 'Toplam Gider',
    
    // Table headers
    categoryCode: 'Kod',
    category: 'Kategori',
    amount: 'Tutar',
    vatAmount: 'KDV',
    totalAmount: 'Toplam',
    transactionCount: 'Adet',
    
    // Period labels
    period: 'Rapor Dönemi',
    taxYear: 'Vergi Yılı',
    from: 'Başlangıç',
    to: 'Bitiş',
    generatedOn: 'Oluşturulma Tarihi',
    
    // Monthly breakdown
    month: 'Ay',
    monthlyIncome: 'Gelir',
    monthlyExpenses: 'Gider',
    monthlyNetProfit: 'Net Kar',
    
    // Footer
    footer: {
      disclaimer: 'Bu rapor yalnızca bilgilendirme amaçlıdır ve profesyonel vergi tavsiyesi niteliği taşımaz.',
      confidential: 'Gizli',
      generatedBy: 'UK Muhasebe Sistemi tarafından oluşturulmuştur'
    }
  }
};

/**
 * Gets labels for a specific language.
 * 
 * @param {string} [lang='en'] - Language code ('en' or 'tr')
 * @returns {Object} Labels for the specified language
 */
function getLabels(lang = 'en') {
  return labels[lang] || labels.en;
}

/**
 * Gets month name in the specified language.
 * 
 * @param {number} month - Month number (1-12)
 * @param {string} [lang='en'] - Language code
 * @returns {string} Month name
 */
function getMonthName(month, lang = 'en') {
  const monthNames = {
    en: [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ],
    tr: [
      'Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran',
      'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık'
    ]
  };
  const names = monthNames[lang] || monthNames.en;
  return names[month - 1] || '';
}

/**
 * PDF color theme for Profit & Loss reports.
 * @type {Object}
 */
const colors = {
  primary: '#1a365d',        // Dark blue for headers
  secondary: '#2b6cb0',      // Medium blue for accents
  text: '#1a202c',           // Near black for main text
  textLight: '#4a5568',      // Gray for secondary text
  border: '#e2e8f0',         // Light gray for borders
  background: '#f7fafc',     // Very light gray for backgrounds
  headerBg: '#edf2f7',       // Light blue-gray for table headers
  white: '#ffffff',
  
  // Report-specific colors
  income: '#38a169',         // Green for income
  expense: '#e53e3e',        // Red for expenses
  positive: '#38a169',       // Green for positive values
  negative: '#e53e3e',       // Red for negative values
  neutral: '#718096'         // Gray for neutral values
};

/**
 * PDF font settings.
 * @type {Object}
 */
const fonts = {
  regular: 'Helvetica',
  bold: 'Helvetica-Bold',
  italic: 'Helvetica-Oblique',
  boldItalic: 'Helvetica-BoldOblique'
};

/**
 * PDF layout settings for Profit & Loss reports.
 * @type {Object}
 */
const layout = {
  pageSize: 'A4',
  margins: {
    top: 50,
    bottom: 50,
    left: 50,
    right: 50
  },
  
  // Section spacing
  sectionSpacing: 25,
  lineSpacing: 5,
  
  // Table settings
  tableHeaderHeight: 22,
  tableRowHeight: 18,
  
  // Font sizes
  fontSize: {
    title: 18,
    subtitle: 12,
    sectionTitle: 12,
    tableHeader: 9,
    tableCell: 9,
    footer: 8
  }
};

module.exports = {
  labels,
  getLabels,
  getMonthName,
  colors,
  fonts,
  layout
};
