/**
 * VAT Return Template
 * Provides bilingual (English/Turkish) labels and formatting for UK HMRC VAT returns.
 * 
 * All VAT return labels and text strings are provided in both languages.
 * UK-specific requirements including all nine HMRC boxes are included.
 * 
 * HMRC VAT Return Boxes:
 * - Box 1: VAT due on sales and other outputs
 * - Box 2: VAT due on acquisitions from EU (legacy, now 0 post-Brexit)
 * - Box 3: Total VAT due (Box 1 + Box 2)
 * - Box 4: VAT reclaimed on purchases and other inputs
 * - Box 5: Net VAT to pay or reclaim (Box 3 - Box 4)
 * - Box 6: Total value of sales and outputs (excluding VAT)
 * - Box 7: Total value of purchases and inputs (excluding VAT)
 * - Box 8: Total value of supplies to EU (excluding VAT)
 * - Box 9: Total value of acquisitions from EU (excluding VAT)
 * 
 * @module templates/vatReturn
 */

/**
 * VAT return labels in both languages.
 * @type {Object}
 */
const labels = {
  en: {
    // Document title
    title: 'VAT RETURN',
    subtitle: 'For Record-Keeping and HMRC Submission Reference',
    
    // Header labels
    periodLabel: 'VAT Period',
    periodFrom: 'From',
    periodTo: 'To',
    generatedOn: 'Generated on',
    referenceNumber: 'Reference Number',
    status: 'Status',
    
    // Status labels
    statuses: {
      draft: 'DRAFT',
      pending: 'PENDING',
      submitted: 'SUBMITTED',
      accepted: 'ACCEPTED',
      rejected: 'REJECTED',
      amended: 'AMENDED'
    },
    
    // Business details
    businessDetails: 'Business Details',
    businessName: 'Business Name',
    vatNumber: 'VAT Registration Number',
    companyNumber: 'Company Registration Number',
    businessAddress: 'Business Address',
    email: 'Email',
    
    // VAT boxes section
    vatBoxesTitle: 'VAT Return Details',
    vatOutputSection: 'VAT Output (Collected)',
    vatInputSection: 'VAT Input (Reclaimed)',
    vatSummarySection: 'VAT Summary',
    salesPurchasesSection: 'Sales and Purchases',
    euTradeSection: 'EU Trade (Post-Brexit)',
    
    // Box labels
    box1Label: 'Box 1',
    box1Description: 'VAT due on sales and other outputs',
    box2Label: 'Box 2',
    box2Description: 'VAT due on acquisitions from EU member states',
    box3Label: 'Box 3',
    box3Description: 'Total VAT due (Box 1 + Box 2)',
    box4Label: 'Box 4',
    box4Description: 'VAT reclaimed on purchases and other inputs',
    box5Label: 'Box 5',
    box5Description: 'Net VAT to pay to HMRC (or reclaim)',
    box6Label: 'Box 6',
    box6Description: 'Total value of sales and all other outputs excluding VAT',
    box7Label: 'Box 7',
    box7Description: 'Total value of purchases and all other inputs excluding VAT',
    box8Label: 'Box 8',
    box8Description: 'Total value of all supplies of goods to EU member states',
    box9Label: 'Box 9',
    box9Description: 'Total value of all acquisitions of goods from EU member states',
    
    // Summary labels
    netVatPayable: 'Net VAT Payable',
    netVatRefund: 'Net VAT Refund Due',
    
    // Notes section
    notes: 'Notes',
    
    // Footer
    disclaimer: 'IMPORTANT: This document is for record-keeping purposes only. For official HMRC submission, use the Government Gateway portal or Making Tax Digital (MTD) compatible software. The figures in this document should be verified before official submission. This is not an official HMRC document.',
    thankYou: 'Generated by UK Pre-Accounting System',
    
    // Currency
    currency: {
      GBP: '£',
      EUR: '€',
      USD: '$'
    }
  },
  
  tr: {
    // Document title
    title: 'KDV BEYANNAMESI',
    subtitle: 'Kayıt Tutma ve HMRC Başvuru Referansı İçin',
    
    // Header labels
    periodLabel: 'KDV Dönemi',
    periodFrom: 'Başlangıç',
    periodTo: 'Bitiş',
    generatedOn: 'Oluşturulma tarihi',
    referenceNumber: 'Referans Numarası',
    status: 'Durum',
    
    // Status labels
    statuses: {
      draft: 'TASLAK',
      pending: 'BEKLEMEDE',
      submitted: 'GÖNDERİLDİ',
      accepted: 'KABUL EDİLDİ',
      rejected: 'REDDEDİLDİ',
      amended: 'DEĞİŞTİRİLDİ'
    },
    
    // Business details
    businessDetails: 'İşletme Bilgileri',
    businessName: 'İşletme Adı',
    vatNumber: 'KDV Sicil Numarası',
    companyNumber: 'Şirket Sicil Numarası',
    businessAddress: 'İşletme Adresi',
    email: 'E-posta',
    
    // VAT boxes section
    vatBoxesTitle: 'KDV Beyanname Detayları',
    vatOutputSection: 'Hesaplanan KDV (Toplanan)',
    vatInputSection: 'İndirilecek KDV (Mahsup)',
    vatSummarySection: 'KDV Özeti',
    salesPurchasesSection: 'Satışlar ve Alımlar',
    euTradeSection: 'AB Ticareti (Brexit Sonrası)',
    
    // Box labels
    box1Label: 'Kutu 1',
    box1Description: 'Satışlar ve diğer çıktılar üzerinden hesaplanan KDV',
    box2Label: 'Kutu 2',
    box2Description: 'AB üye devletlerinden edinimler üzerinden hesaplanan KDV',
    box3Label: 'Kutu 3',
    box3Description: 'Toplam hesaplanan KDV (Kutu 1 + Kutu 2)',
    box4Label: 'Kutu 4',
    box4Description: 'Alımlar ve diğer girdiler üzerinden indirilecek KDV',
    box5Label: 'Kutu 5',
    box5Description: 'HMRC\'ye ödenecek net KDV (veya iade alınacak)',
    box6Label: 'Kutu 6',
    box6Description: 'KDV hariç satışlar ve tüm diğer çıktıların toplam değeri',
    box7Label: 'Kutu 7',
    box7Description: 'KDV hariç alımlar ve tüm diğer girdilerin toplam değeri',
    box8Label: 'Kutu 8',
    box8Description: 'AB üye devletlerine yapılan tüm mal teslimlerinin toplam değeri',
    box9Label: 'Kutu 9',
    box9Description: 'AB üye devletlerinden yapılan tüm mal edinimlerinin toplam değeri',
    
    // Summary labels
    netVatPayable: 'Ödenecek Net KDV',
    netVatRefund: 'İade Alınacak Net KDV',
    
    // Notes section
    notes: 'Notlar',
    
    // Footer
    disclaimer: 'ÖNEMLİ: Bu belge yalnızca kayıt tutma amaçlıdır. Resmi HMRC başvurusu için Government Gateway portalını veya Making Tax Digital (MTD) uyumlu yazılımı kullanın. Bu belgedeki rakamlar resmi başvurudan önce doğrulanmalıdır. Bu resmi bir HMRC belgesi değildir.',
    thankYou: 'UK Pre-Accounting Sistemi tarafından oluşturuldu',
    
    // Currency
    currency: {
      GBP: '£',
      EUR: '€',
      USD: '$'
    }
  }
};

/**
 * Gets labels for a specific language.
 * 
 * @param {string} [lang='en'] - Language code ('en' or 'tr')
 * @returns {Object} Labels for the specified language
 */
function getLabels(lang = 'en') {
  return labels[lang] || labels.en;
}

/**
 * Gets the currency symbol for a currency code.
 * 
 * @param {string} currencyCode - Currency code (GBP, EUR, USD)
 * @param {string} [lang='en'] - Language code
 * @returns {string} Currency symbol
 */
function getCurrencySymbol(currencyCode, lang = 'en') {
  const l = getLabels(lang);
  return l.currency[currencyCode] || currencyCode + ' ';
}

/**
 * Gets the status display label.
 * 
 * @param {string} status - VAT return status
 * @param {string} [lang='en'] - Language code
 * @returns {string} Status display label
 */
function getStatusLabel(status, lang = 'en') {
  const l = getLabels(lang);
  return l.statuses[status] || status.toUpperCase();
}

/**
 * PDF color theme for VAT returns.
 * @type {Object}
 */
const colors = {
  primary: '#1a365d',        // Dark blue for headers
  secondary: '#2b6cb0',      // Medium blue for accents
  text: '#1a202c',           // Near black for main text
  textLight: '#4a5568',      // Gray for secondary text
  border: '#e2e8f0',         // Light gray for borders
  background: '#f7fafc',     // Very light gray for backgrounds
  headerBg: '#edf2f7',       // Light blue-gray for table headers
  white: '#ffffff',
  warning: '#c05621',        // Orange for warnings/disclaimer
  success: '#276749',        // Green for positive values
  danger: '#c53030',         // Red for negative values/refunds
  
  // Status colors
  statusDraft: '#718096',     // Gray
  statusPending: '#d69e2e',   // Amber
  statusSubmitted: '#2b6cb0', // Blue
  statusAccepted: '#38a169',  // Green
  statusRejected: '#e53e3e',  // Red
  statusAmended: '#805ad5'    // Purple
};

/**
 * Gets the color for a VAT return status.
 * 
 * @param {string} status - VAT return status
 * @returns {string} Hex color code
 */
function getStatusColor(status) {
  const statusColors = {
    draft: colors.statusDraft,
    pending: colors.statusPending,
    submitted: colors.statusSubmitted,
    accepted: colors.statusAccepted,
    rejected: colors.statusRejected,
    amended: colors.statusAmended
  };
  return statusColors[status] || colors.textLight;
}

/**
 * PDF font settings.
 * @type {Object}
 */
const fonts = {
  // Use built-in fonts for pdfkit
  regular: 'Helvetica',
  bold: 'Helvetica-Bold',
  italic: 'Helvetica-Oblique',
  boldItalic: 'Helvetica-BoldOblique'
};

/**
 * PDF layout settings.
 * @type {Object}
 */
const layout = {
  pageSize: 'A4',
  margins: {
    top: 50,
    bottom: 70,  // More space for disclaimer footer
    left: 50,
    right: 50
  },
  
  // Header dimensions
  headerHeight: 80,
  
  // Table settings
  boxRowHeight: 40,
  sectionHeaderHeight: 28,
  
  // Spacing
  sectionSpacing: 20,
  lineSpacing: 5
};

module.exports = {
  labels,
  getLabels,
  getCurrencySymbol,
  getStatusLabel,
  getStatusColor,
  colors,
  fonts,
  layout
};
